x-common-config: &common-config
  image: registry.cn-guangzhou.aliyuncs.com/jonluo/openjarvis:latest
  volumes:
    - ./.nanobot:/root/.nanobot
  env_file:
    - .env

services:
  nanobot-server:
    container_name: nanobot-server
    <<: *common-config
    command: [ "server" ]
    restart: unless-stopped
    ports:
      - 18790:18790
      - 4096:4096
