x-common-config: &common-config
  image: openjarvis:latest
  restart: unless-stopped

services:
  openjarvis-server:
    container_name: openjarvis-server
    <<: *common-config
    volumes:
      - ./.nanobot:/root/.nanobot
    env_file:
      - .env1
    command: [ "server" ]
    ports:
      - 18790:18790
      - 4096:4096

  openjarvis-server2:
    container_name: openjarvis-server2
    <<: *common-config
    volumes:
      - ./.nanobot2:/root/.nanobot
    env_file:
      - .env2
    command: [ "server" ]
    ports:
      - 18791:18790
      - 4097:4096
